spring:
  profiles:
    active: dev
  # 开发环境数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/ai_commerce_order?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
