server:
  port: 8080
spring:
  application:
    name: 2025-ai-commerce-order
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/ai_commerce_order?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        hbm2ddl:
          auto: none

springdoc:
  swagger-ui:
    path: /
  api-docs:
    enabled: true
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,env,beans,configprops  # 暴露所有需要的端点
      base-path: /actuator  # 基础路径
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name} # 给指标添加服务名称标签，方便多服务区分
    distribution:
      percentiles-histogram:
        http.server.requests: true  # 启用请求延迟直方图

logging:
  file:
    name: /app/logs/app.log  # 容器内日志文件路径
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # 控制台日志格式


