spring:
  profiles:
    active: dev
  # 开发环境数据库配置
  datasource:
    url: jdbc:mysql://2025_ai_agent_infrastructure_mysql:3306/ai_commerce_order?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
