spring:
  # 开发环境数据库配置
  datasource:
    url: jdbc:mysql://2025_ai_agent_infrastructure_mysql:3306/ai_commerce_order?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
